name: bForStrain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - pyvista
  - scipy
  - pyproj
  - geopandas
  - pip
  - pip:
    - triangle
    - ismember
